mybatis:
  mapper-locations:
    type-aliases-package: com.example.yeomanbg
    configuration:
      map-underscore-to-camel-case: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
logging:
  config: classpath:logback.xml
  level:
    root: info
